apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: capk-controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: capk-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: capk-controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: "manager"
      labels:
        control-plane: capk-controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - "--metrics-bind-addr=127.0.0.1:8080"
        - "--leader-elect"
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
