on: [push, pull_request]
name: build
jobs:
  unit_test:
    if: (github.repository == 'kubernetes-sigs/cluster-api-provider-kubemark')
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Build
      run: make manager

  go-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.48.0
        working-directory: ${{matrix.working-directory}}
